config/routes.rb
PizzariaMon::Application.routes.draw do
  resources :item_pedidos

  resources :pedidos

  resources :pizzas

  resources :usuarios

  resources :clientes

  get "login/login"

  root  :to => "login#index"

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :pedido

	attr_accessible :endereco, :nome, :telefone

	validates :endereco, presence: true
	validates :nome, presence: true
	validates :telefone , presence: true
	
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente criado com sucesso.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.number_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Endereco</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.endereco %></td>
    <td><%= cliente.telefone %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>Cadastrar Cliente</h1>

<%= render 'form' %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Endereco:</b>
  <%= @cliente.endereco %>
</p>

<p>
  <b>Telefone:</b>
  <%= @cliente.telefone %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>