config/routes.rb
PizzariaMon::Application.routes.draw do
  resources :item_pedidos

  resources :pedidos

  resources :pizzas

  resources :usuarios

  resources :clientes

  get "login/login"

  root  :to => "login#index"

end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
  attr_accessible :sabor, :valor
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pizzas }
    end
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
    @pizza = Pizza.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pizza }
    end
  end

  # GET /pizzas/new
  # GET /pizzas/new.json
  def new
    @pizza = Pizza.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pizza }
    end
  end

  # GET /pizzas/1/edit
  def edit
    @pizza = Pizza.find(params[:id])
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(params[:pizza])

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render json: @pizza, status: :created, location: @pizza }
      else
        format.html { render action: "new" }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pizzas/1
  # PUT /pizzas/1.json
  def update
    @pizza = Pizza.find(params[:id])

    respond_to do |format|
      if @pizza.update_attributes(params[:pizza])
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza = Pizza.find(params[:id])
    @pizza.destroy

    respond_to do |format|
      format.html { redirect_to pizzas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sabor %><br />
    <%= f.text_field :sabor %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/index.html.erb
<h1>Listing pizzas</h1>

<table>
  <tr>
    <th>Sabor</th>
    <th>Valor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pizzas.each do |pizza| %>
  <tr>
    <td><%= pizza.sabor %></td>
    <td><%= pizza.valor %></td>
    <td><%= link_to 'Show', pizza %></td>
    <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
    <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pizza', new_pizza_path %>

app/views/pizzas/new.html.erb
<h1>New pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sabor:</b>
  <%= @pizza.sabor %>
</p>

<p>
  <b>Valor:</b>
  <%= @pizza.valor %>
</p>


<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>