config/routes.rb
PizzariaMon::Application.routes.draw do
  resources :item_pedidos

  resources :pedidos

  resources :pizzas

  resources :usuarios

  resources :clientes

  get "login/login"

  root  :to => "login#index"

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :cliente
  has_many :item_pedido

  attr_accessible :data, :status, :total
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pedidos }
    end
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/new
  # GET /pedidos/new.json
  def new
    @pedido = Pedido.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/1/edit
  def edit
    @pedido = Pedido.find(params[:id])
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(params[:pedido])

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render json: @pedido, status: :created, location: @pedido }
      else
        format.html { render action: "new" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pedidos/1
  # PUT /pedidos/1.json
  def update
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      if @pedido.update_attributes(params[:pedido])
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido = Pedido.find(params[:id])
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to pedidos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% @pedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Listing pedidos</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Status</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pedidos.each do |pedido| %>
  <tr>
    <td><%= pedido.data %></td>
    <td><%= pedido.status %></td>
    <td><%= pedido.total %></td>
    <td><%= link_to 'Show', pedido %></td>
    <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
    <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @pedido.data %>
</p>

<p>
  <b>Status:</b>
  <%= @pedido.status %>
</p>

<p>
  <b>Total:</b>
  <%= @pedido.total %>
</p>


<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>