config/routes.rb
PizzariaMon::Application.routes.draw do
  resources :item_pedidos

  resources :pedidos

  resources :pizzas

  resources :usuarios

  resources :clientes

  get "login/login"

  root  :to => "login#index"

end

app/models/item_pedido.rb
class ItemPedido < ActiveRecord::Base  
  belongs_to :pedido
  has_many :pizza

  attr_accessible :observacao, :quantidade, :valor

  validates :quantidade, presense: true
end

app/controllers/item_pedidos_controller.rb
class ItemPedidosController < ApplicationController
  # GET /item_pedidos
  # GET /item_pedidos.json
  def index
    @item_pedidos = ItemPedido.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @item_pedidos }
    end
  end

  # GET /item_pedidos/1
  # GET /item_pedidos/1.json
  def show
    @item_pedido = ItemPedido.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item_pedido }
    end
  end

  # GET /item_pedidos/new
  # GET /item_pedidos/new.json
  def new
    @item_pedido = ItemPedido.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item_pedido }
    end
  end

  # GET /item_pedidos/1/edit
  def edit
    @item_pedido = ItemPedido.find(params[:id])
  end

  # POST /item_pedidos
  # POST /item_pedidos.json
  def create
    @item_pedido = ItemPedido.new(params[:item_pedido])

    respond_to do |format|
      if @item_pedido.save
        format.html { redirect_to @item_pedido, notice: 'Item pedido was successfully created.' }
        format.json { render json: @item_pedido, status: :created, location: @item_pedido }
      else
        format.html { render action: "new" }
        format.json { render json: @item_pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /item_pedidos/1
  # PUT /item_pedidos/1.json
  def update
    @item_pedido = ItemPedido.find(params[:id])

    respond_to do |format|
      if @item_pedido.update_attributes(params[:item_pedido])
        format.html { redirect_to @item_pedido, notice: 'Item pedido was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item_pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_pedidos/1
  # DELETE /item_pedidos/1.json
  def destroy
    @item_pedido = ItemPedido.find(params[:id])
    @item_pedido.destroy

    respond_to do |format|
      format.html { redirect_to item_pedidos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/item_pedidos_helper.rb
module ItemPedidosHelper
end

app/views/item_pedidos/_form.html.erb
<%= form_for(@item_pedido) do |f| %>
  <% if @item_pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_pedido.errors.count, "error") %> prohibited this item_pedido from being saved:</h2>

      <ul>
      <% @item_pedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantidade %><br />
    <%= f.number_field :quantidade %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :observacao %><br />
    <%= f.text_field :observacao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_pedidos/edit.html.erb
<h1>Editing item_pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_pedido %> |
<%= link_to 'Back', item_pedidos_path %>

app/views/item_pedidos/index.html.erb
<h1>Listing item_pedidos</h1>

<table>
  <tr>
    <th>Quantidade</th>
    <th>Valor</th>
    <th>Observacao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @item_pedidos.each do |item_pedido| %>
  <tr>
    <td><%= item_pedido.quantidade %></td>
    <td><%= item_pedido.valor %></td>
    <td><%= item_pedido.observacao %></td>
    <td><%= link_to 'Show', item_pedido %></td>
    <td><%= link_to 'Edit', edit_item_pedido_path(item_pedido) %></td>
    <td><%= link_to 'Destroy', item_pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item pedido', new_item_pedido_path %>

app/views/item_pedidos/new.html.erb
<h1>New item_pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', item_pedidos_path %>

app/views/item_pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quantidade:</b>
  <%= @item_pedido.quantidade %>
</p>

<p>
  <b>Valor:</b>
  <%= @item_pedido.valor %>
</p>

<p>
  <b>Observacao:</b>
  <%= @item_pedido.observacao %>
</p>


<%= link_to 'Edit', edit_item_pedido_path(@item_pedido) %> |
<%= link_to 'Back', item_pedidos_path %>